### PR TITLE
Development to main

### PR DESCRIPTION
**Pull request by darwin808**
change nav layout 
move tabs navigation into appbar
added code helper tab 

image
image

### CODE REVIEW

**Comment by ardeay** [comment]
@darwin808 please post an example of the zesty links: dropdown

**Comment by darwin808** [comment]
image
dropdown

**Comment by ardeay** [comment]
Change `Zesty Link` to `Manager Links`

**Comment by darwin808** [comment]
@ardeay already remove the extra files in dist folder

**Pull request merged**
